### ISSUE TITLE
Example for (Java-)dummies

### ISSUE THREAD

**Issue by larskluge** [ptgoetz/flux#10]
This is an awesome project and I'd love to use it, but having issues to get rolling. An example for dummies would be very much appreciated, an approach here: 

```
git clone https://github.com/ptgoetz/flux.git
cd flux/flux-examples
mvn package
storm jar ./target/flux-examples-0.2.3-SNAPSHOT.jar org.apache.storm.flux.Flux --remote ./target/classes/simple_wordcount.yaml -c nimbus.host=localdocker -c nimbus.thrift.port=49627
```

Unfortunately this fails with `Error: Could not find or load main class org.apache.storm.flux.Flux`

Any help is very much appreciated. More sophisticated issues from here on—promised. Thank you.

**Comment by ptgoetz** [comment]
@larskluge Thank for pointing this out. I've fixed the examples packaging and added a README per your suggestion.

If you update from master and to a `mvn install` from the `flux` directory, you should be good to go.

**Comment by larskluge** [comment]
Sweet—works like a charm :) Thanks a ton @ptgoetz
