### ISSUE TITLE
Mention requirement for Python and Node in description for build purposes.

### ISSUE THREAD

**Issue by rmkellogg** [ptgoetz/flux#11]
In order to build the project, Python and node must be installed on the client.  Unfortunately not a given on Windows.

**Comment by ptgoetz** [comment]
Thanks for pointing this out @rmkellogg. Should be fixed quickly...

**Comment by ptgoetz** [comment]
Fixed in master.

**Comment by rmkellogg** [comment]
Looks good thanks.
