### ISSUE TITLE
NoSuchMethod Error , When Running On Cluster Mode

### ISSUE THREAD

**Issue by SanthoshPrasad** [ptgoetz/flux#9]
**Strom Version: 0.9.3.2.2.0.0-2041**
**HDP: 2.2**

Getting the following exception:

264  [main] INFO  org.apache.storm.flux.Flux - Running remotely...
264  [main] INFO  org.apache.storm.flux.Flux - Deploying topology in an 
ACTIVE state...
Exception in thread "main" java.lang.NoSuchMethodError: 
backtype.storm.StormSubmitter.submitTopology(Ljava/lang/String;Ljava/util/Map;Lbacktype/storm/generated/StormTopology;Lbacktype/storm/generated/SubmitOptions;)V
     at org.apache.storm.flux.Flux.runCli(Flux.java:148)
     at org.apache.storm.flux.Flux.main(Flux.java:87)

It's got resolved after removing fourth argument(submitOptions)  from the following function call **StormSubmitter.submitTopology(topologyName, conf, topology,submitOptions)**, it seems in the above version of storm this method is not available.

**And also please update maven artifact for version 0.2.2**

**Comment by ptgoetz** [comment]
Thanks for pointing that out. I will fix it and push out a new release.

**Comment by ptgoetz** [comment]
Fixed and released as 0.2.2.

**Comment by SanthoshPrasad** [comment]
Thanks, by the way flux is an excellent  initiative.
